account_id = "049ff5e84ecf636b53b162cbb580aae6"
name = "legacy-ai"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "STATE"
id = "a7531b439a174618a2cc44d015cdd3d7"
